feat : CI detekt 정적분석 사용

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -24,3 +24,14 @@ jobs:
       run: chmod +x gradlew
     - name: Build with Gradle
       run: ./gradlew build
+      
+    - name: Run detekt
+      run: ./gradlew detekt
+
+      # Make sure we always run this upload task,
+      # because the previous step may fail if there are findings.
+    - name: Upload SARIF to GitHub using the upload-sarif action
+      uses: github/codeql-action/upload-sarif@v2
+      if: success() || failure()
+      with:
+        sarif_file: build/reports/detekt/detekt.sarif
